name: pry_transcontrol
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.4.10
  equatable: ^2.0.5

  google_fonts: ^8.1.0
  flutter_animate: ^4.0.0

flutter:
  uses-material-design: true
